# Generated by Django 4.2.24 on 2025-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('cutomer', 'Customer'), ('vendor', 'Vendor'), ('employee', 'Employee'), ('bank', 'Bank')], max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contact_info', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
