# Generated by Django 4.2.24 on 2025-09-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('employee', 'Employee'), ('bank', 'Bank')], max_length=20),
        ),
    ]
